version: '3'
services:
  load-balancer:
    build: .
    ports:
      - 8000:8000
    networks:
      - lb-net
    depends_on:
      - server1
      - server2
      - server3
      - mock-server1
      - mock-server2
      - mock-server3
    environment:
      - ZIPKIN_SERVER_URL=http://192.168.1.8:9411/api/v2/spans

  server1:
    build: ./server1
    ports:
      - 8001:8001
    networks:
      - lb-net

  server2:
    build: ./server2
    ports:
      - 8002:8002
    networks:
      - lb-net

  server3:
    build: ./server3
    ports:
      - 8003:8003
    networks:
      - lb-net

  mock-server1:
    image: rodolpheche/wiremock
    volumes:
      - ./mappings1:/home/wiremock/mappings
    ports:
      - 8004:8080
    networks:
      - lb-net

  mock-server2:
    image: rodolpheche/wiremock
    volumes:
      - ./mappings2:/home/wiremock/mappings
    ports:
      - 8005:8080
    networks:
      - lb-net

  mock-server3:
    image: rodolpheche/wiremock
    volumes:
      - ./mappings3:/home/wiremock/mappings
    ports:
      - 8006:8080
    networks:
      - lb-net

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - lb-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - lb-net
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - 192.168.1.8:8899:8080
    networks:
      - lb-net
    volumes:
      - ./mappings:/home/wiremock/mappings - lb-net

networks:
  lb-net:
